name: aria
description: "A client app for Misskey, a federated social media platform."
publish_to: 'none'
version: 0.13.4+34

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  aho_corasick: ^2.0.0
  audio_service: ^0.18.15
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.3.1
  characters: ^1.3.0
  chewie: ^1.8.1
  collection: ^1.18.0
  colorfilter_generator: ^0.0.8
  confetti: ^0.7.0
  connectivity_plus: ^6.0.3
  dio: ^5.5.0+1
  dotted_border: ^2.1.0
  extended_image: ^8.2.1
  file: ^7.0.0
  file_picker: ^8.0.5
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.3.3
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_hooks: ^0.20.5
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.0.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  flutter_rust_bridge: 2.0.0-dev.38
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.4
  gal: ^2.3.0
  go_router: ^14.2.1
  highlighting: ^0.9.0+11.8.0
  hooks_riverpod: ^2.5.1
  image: ^4.2.0
  image_compression: ^1.0.5
  image_editor: ^1.5.1
  image_size_getter: ^2.1.3
  intl: ^0.18.1
  json5: ^0.8.2
  json_annotation: ^4.9.0
  just_audio: ^0.9.39
  kana_kit: ^2.0.0
  keyboard_attachable: ^2.2.0
  mfm_parser:
    git:
      url: https://github.com/poppingmoon/dart_mfm_parser
      ref: 8b0fb47a3de30fbb23f95282969ed1a653b112e9
  mime: ^1.0.5
  misskey_dart:
    git:
      url: https://github.com/poppingmoon/misskey_dart
      ref: 3e59e8e8b1499332d4f7f30a48582cd45a61b0a0
  multi_split_view: ^3.2.2
  package_info_plus: ^8.0.0
  photo_view: ^0.15.0
  pretty_bytes: ^6.1.0
  punycode: ^1.0.0
  receive_sharing_intent: ^1.8.0
  reorderable_grid: ^1.0.10
  reorderables: ^0.6.0
  riverpod_annotation: ^2.3.5
  rust_lib_aria:
    path: rust_builder
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  tinycolor2:
    git:
      url: https://github.com/poppingmoon/tinycolor2
      ref: 030e8d5f6167071016ebc9fe7359003a4f78dcc3
  twemoji_v2:
    git:
      url: https://github.com/poppingmoon/twemoji_v2
      ref: 4e9421350c0f6b3c4ca908e79042e6a2ab5d6dfc
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  vector_math: ^2.1.4
  video_player: ^2.9.1
  wakelock_plus: ^1.2.5
  web_socket_channel: ^2.4.5

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  http_mock_adapter: ^0.6.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lint: ^2.3.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.31.0
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/BIZ_UDGothic/
    - assets/fonts/BIZ_UDMincho/
    - assets/fonts/Mplus1/
    - assets/fonts/Mplus2/
    - assets/fonts/Noto_Sans_JP/
    - assets/fonts/Noto_Sans_KR/
    - assets/fonts/Noto_Sans_SC/
    - assets/fonts/Noto_Sans_TC/
    - assets/fonts/Noto_Serif_JP/
    - assets/fonts/Nunito/
    - assets/fonts/Pretendard/
    - assets/misskey/COPYING
    - assets/misskey/LICENSE
    - assets/misskey/packages/frontend/assets/
  fonts:
    - family: BIZ UDGothic
      fonts:
        - asset: assets/fonts/BIZ_UDGothic/BIZUDGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/BIZ_UDGothic/BIZUDGothic-Bold.ttf
          weight: 700
    - family: BIZ UDMincho
      fonts:
        - asset: assets/fonts/BIZ_UDMincho/BIZUDMincho-Regular.ttf
          weight: 400
        - asset: assets/fonts/BIZ_UDMincho/BIZUDMincho-Bold.ttf
          weight: 700
    - family: M PLUS 1
      fonts:
        - asset: assets/fonts/Mplus1/Mplus1-Regular.otf
          weight: 400
        - asset: assets/fonts/Mplus1/Mplus1-Bold.otf
          weight: 700
    - family: M PLUS 2
      fonts:
        - asset: assets/fonts/Mplus2/Mplus2-Regular.otf
          weight: 400
        - asset: assets/fonts/Mplus2/Mplus2-Bold.otf
          weight: 700
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.ttf
          weight: 700
    - family: Noto Sans KR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.ttf
          weight: 700
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Bold.ttf
          weight: 700
    - family: Noto Sans TC
      fonts:
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-Bold.ttf
          weight: 700
    - family: Noto Serif JP
      fonts:
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Bold.otf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/aria.png"
  android: true
  adaptive_icon_foreground: "assets/aria_android.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
  macos:
    generate: true
