name: aria
description: "A client app for Misskey, a federated social media platform."
publish_to: "none"
version: 1.3.4+73

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  aho_corasick: ^2.0.0
  async: ^2.13.0
  audio_service: ^0.18.18
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  characters: ^1.4.0
  chewie: ^1.12.1
  collection: ^1.19.1
  colorfilter_generator: ^0.0.8
  confetti: ^0.8.0
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  dotted_border: ^3.1.0
  extended_image: ^10.0.1
  file: ^7.0.1
  file_picker: ^10.2.1
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  flutter_apns_only:
    git:
      url: https://github.com/poppingmoon/flutter-apns
      ref: 1911c4f5fd1bd6d10361561916f8ec15ab6e8dbb
      path: flutter_apns_only
  flutter_blurhash: ^0.9.1
  flutter_cache_manager: ^3.4.1
  flutter_highlighting:
    git:
      url: https://github.com/poppingmoon/dart-highlighting
      ref: 11a5b3a455973c5021401725c4866b811b4a088f
      path: flutter_highlighting
  flutter_hooks: ^0.21.2
  flutter_html: ^3.0.0
  flutter_image_compress: ^2.4.0
  flutter_inappwebview: ^6.1.5
  flutter_inset_shadow: ^2.0.3
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  flutter_rust_bridge: 2.11.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.1.0
  gal: ^2.3.2
  gal_linux: ^0.1.2
  go_router: ^16.1.0
  highlighting:
    git:
      url: https://github.com/poppingmoon/dart-highlighting
      ref: cabd93636e331707ad6ff0f548a9c21e07b0e6c7
      path: highlighting
  hooks_riverpod: ^2.6.1
  image: ^4.5.4
  image_compression:
    git:
      url: https://github.com/poppingmoon/image_compression
      ref: 37b78624635c42f51524cdfc001ae9073ec468ee
  image_editor: ^1.6.0
  intl: ^0.20.2
  json5: ^0.8.2
  json_annotation: ^4.9.0
  just_audio: ^0.10.4
  kana_kit: ^2.1.1
  material_off_icons:
    git:
      url: https://github.com/poppingmoon/material_off_icons
      ref: d2ba3655f1104ed628cf9ecd88f603d71b92d90a
  material_symbols_icons: ^4.2858.1
  mfm_parser:
    git:
      url: https://github.com/poppingmoon/dart_mfm_parser
      ref: 1b9072e84c2437ebe13237dca7ff82c1e74520a1
  mime: ^2.0.0
  misskey_dart:
    git:
      url: https://github.com/poppingmoon/misskey_dart
      ref: a9704f10ffe7b2c195741f54e8b6c59b3fabdf57
  multi_split_view: ^3.6.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  punycode: ^1.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  reorderable_grid: ^1.0.10
  reorderables: ^0.6.0
  riverpod_annotation: ^2.6.1
  rust_lib_aria:
    path: rust_builder
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shared_preferences_platform_interface: ^2.4.1
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  tinycolor2:
    git:
      url: https://github.com/poppingmoon/tinycolor2
      ref: 030e8d5f6167071016ebc9fe7359003a4f78dcc3
  twemoji_v2:
    git:
      url: https://github.com/poppingmoon/twemoji_v2
      ref: 34eb94b6837386144b25cb02526e398b4d83fe06
  unifiedpush: ^6.0.2
  unifiedpush_ui: ^0.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  vector_math: ^2.1.4
  video_player: ^2.10.0
  wakelock_plus: ^1.3.2
  web_socket_channel: ^3.0.3
  webpush_encryption: ^1.0.0-rc1
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  http_mock_adapter: ^0.6.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  lint: ^2.8.0
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.8.0
  url_launcher_platform_interface: ^2.3.2
  yaml: ^3.1.3

dependency_overrides:
  flutter_cache_manager:
    git:
      url: https://github.com/Baseflow/flutter_cache_manager
      ref: 54904e499a06d0364a2b3f4ca9789e5f829f1879
      path: flutter_cache_manager
  unifiedpush_android:
    git:
      url: https://github.com/poppingmoon/flutter-connector
      ref: 90316c05d59da5b31c9861992b07b572e859676f
      path: unifiedpush_android
  webcrypto:
    git:
      url: https://github.com/poppingmoon/webcrypto.dart
      ref: 353eec0336be6ed9d785dd86606b13458456e5bf

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/BIZ_UDGothic/OFL.txt
    - assets/fonts/BIZ_UDMincho/OFL.txt
    - assets/fonts/Mplus1/OFL.txt
    - assets/fonts/Mplus2/OFL.txt
    - assets/fonts/Noto_Sans_JP/OFL.txt
    - assets/fonts/Noto_Sans_KR/OFL.txt
    - assets/fonts/Noto_Sans_SC/OFL.txt
    - assets/fonts/Noto_Sans_TC/OFL.txt
    - assets/fonts/Noto_Serif_JP/OFL.txt
    - assets/fonts/Nunito/OFL.txt
    - assets/fonts/Pretendard/LICENSE.txt
    - assets/misskey/COPYING
    - assets/misskey/LICENSE
    - assets/misskey/packages/frontend/assets/
  fonts:
    - family: BIZ UDGothic
      fonts:
        - asset: assets/fonts/BIZ_UDGothic/BIZUDGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/BIZ_UDGothic/BIZUDGothic-Bold.ttf
          weight: 700
    - family: BIZ UDMincho
      fonts:
        - asset: assets/fonts/BIZ_UDMincho/BIZUDMincho-Regular.ttf
          weight: 400
        - asset: assets/fonts/BIZ_UDMincho/BIZUDMincho-Bold.ttf
          weight: 700
    - family: M PLUS 1
      fonts:
        - asset: assets/fonts/Mplus1/Mplus1-Regular.otf
          weight: 400
        - asset: assets/fonts/Mplus1/Mplus1-Bold.otf
          weight: 700
    - family: M PLUS 2
      fonts:
        - asset: assets/fonts/Mplus2/Mplus2-Regular.otf
          weight: 400
        - asset: assets/fonts/Mplus2/Mplus2-Bold.otf
          weight: 700
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.ttf
          weight: 700
    - family: Noto Sans KR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.ttf
          weight: 700
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Bold.ttf
          weight: 700
    - family: Noto Sans TC
      fonts:
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-Bold.ttf
          weight: 700
    - family: Noto Serif JP
      fonts:
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Bold.otf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/aria.png"
  android: true
  adaptive_icon_foreground: "assets/aria_android.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_monochrome: "assets/aria_android_monochrome.png"
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
  macos:
    generate: true
